package almanac

// import almanac.cn.huangdayu.almanac.AlmanacRunner
// import almanac.cn.huangdayu.almanac.utils.DateTimeUtils
// import almanac.cn.huangdayu.almanac.utils.HistoricalYearUtils
// import almanac.cn.huangdayu.almanac.utils.UnicodeUtils

main() {
    // AlmanacRunner.javaMain([])
    // DateTimeUtils.javaMain([])
    // HistoricalYearUtils.javaMain([])
    // UnicodeUtils.javaMain([])
}